language: node_js

node_js: stable

before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install

script:
  - hexo g

after_script:

  - sed -i "s/cos_appId/${cos_appId}/g" _config.yml
  - sed -i "s/cos_secretId/${cos_secretId}/g" _config.yml
  - sed -i "s/cos_secretKey/${cos_secretKey}/g" _config.yml
  - sed -i "s/cos_bucket/${cos_bucket}/g" _config.yml
  - sed -i "s/gh_token/${GH_TOKEN}/g" _config.yml
  - hexo deploy

branches:
  only:
    - master